### ISSUE TITLE
i10n

### ISSUE THREAD

**Issue by whitebyte** [stonemaster/dlang-tour#199] opened 2016-05-31 10:14 UTC
Hi, 
is there any way to translate the tour into diffrent languages? I'd like to make Russian translation, could you give some guidelines?

**Comment by wilzbach** [comment] 2016-05-31 10:23
Thanks a lot for the offer!
We are currently waiting until the tour gets a bit stable, so that we don't have to redo our efforts. 
See also #132

That being said the only thing that is really blocking at the moment is the switch to separate files - see #137.

**Comment by stonemaster** [comment] 2016-05-31 10:39
This is a duplicate of #132 so closing. Once the number of pull requests drops and feature #137 and #9  are implemented translations may start. You might want to coordinate with @buggins who also voiced interest in a Russian translation.

**Closed by stonemaster** 2016-05-31 10:39 UTC

**Comment by whitebyte** [comment] 2016-05-31 11:41
For some reason I've missed #132, sorry for the noise.
