### ISSUE TITLE
GameDev with D

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#135] opened 2016-05-23 12:10 UTC
I just saw these great slides

http://defenestrate.eu/_static/ossvikend/intro-gamedev-d/slides/index.html

Maybe @kiith-sa wants to make a tour out of them?

**Comment by stonemaster** [comment] 2016-05-25 06:25
This is a duplicate of #27 where ideas may be collected.

**Closed by stonemaster** 2016-05-25 06:25 UTC
